//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jurisdiction.EntityView
{
    using System;
    using System.Collections.Generic;  using Jurisdiction.Entity;
    public partial class Menu
    {
        public Menu()
        {
       
       
        }
    
        public int Mid { get; set; }
        public string MName { get; set; }
        public int ParentId { get; set; }
        public string url { get; set; }
        public string Icon { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Area { get; set; }
        public string Contorll { get; set; }
    
      
      
    }
}
