//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jurisdiction.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.Opration = new HashSet<Opration>();
            this.UserRole = new HashSet<UserRole>();
        }
    
        public int Rid { get; set; }
        public string RName { get; set; }
    
        public virtual ICollection<Opration> Opration { get; set; }
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}
