//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jurisdiction.IBLL
{
    using System;
    using System.Collections.Generic;using Jurisdiction.Entity;
    using Jurisdiction.EntityView;
    using Jurisdiction.Extend;

    public interface OprationIBLL : IBaseBLL<Jurisdiction.Entity.Opration>
    {


        List<OpractionsExtend> GetOpractionByUid(int uid);

        List<OpractionsExtend> GetAllOperaction();

        List<OpractionsExtend> GetOpractionByRoid(int rid);

        /// <summary>
        /// 给指定角色设置权限
        /// </summary>
        /// <param name="rid"></param>
        /// <param name="opraction"></param>
        /// <returns></returns>
        bool SetOpractionByRid(int rid, List<Jurisdiction.Entity.Opration> opraction);
    }
}
