//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jurisdiction.IDAL
{
    using System;
    using System.Collections.Generic;using Jurisdiction.Entity;
    using Jurisdiction.EntityView;
    using Jurisdiction.Extend;

    public interface OprationIDAL : IBaseDAL<Jurisdiction.Entity.Opration>
    {


       /// <summary>
       /// 根据用户id获得权限数据
       /// </summary>
       /// <param name="uid"></param>
       /// <returns></returns>
        List<OpractionsExtend> GetOpractionByUid(int uid);


        /// <summary>
        /// 获得所有的权限数据
        /// </summary>
        /// <returns></returns>
        List<OpractionsExtend> GetAllOperaction();

        /// <summary>
        /// 根据角色id权限数据
        /// </summary>
        /// <param name="rid"></param>
        /// <returns></returns>
        List<OpractionsExtend> GetOpractionByRoid(int rid);

        bool SetOpractionByRid(int rid, List<Jurisdiction.Entity.Opration> opractions);
    }
}
